"""
Django settings for ReefTracker project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from dotenv import load_dotenv, find_dotenv
from pathlib import Path
import os
import dj_database_url


# Build paths inside the project like: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(find_dotenv(filename=".env", usecwd=True))


def normalize_database_url(url: str | None) -> str | None:
    """Convert unsupported dj_database_url schemes to supported ones."""
    if not url:
        return url
    return (
        url.replace("postgresql+psycopg2://", "postgresql://")
           .replace("postgres+psycopg2://", "postgres://")
    )

DATABASE_URL = normalize_database_url(os.environ.get("DATABASE_URL"))
if DATABASE_URL is not None:
    os.environ["DATABASE_URL"] = DATABASE_URL

# ---------- Helpers ----------


def env_list(name: str, default: str = ""):
    """Read a comma-separated env var into a list."""
    return [x.strip() for x in os.environ.get(name, default).split(",") if x.strip()]


# ---------- Security / Debug ----------
# Keep the real key in environment (Codespaces/Render). Fallback is dev-only.
SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key")

# DEBUG=1 (true) / DEBUG=0 (false)
DEBUG = os.environ.get("DEBUG", "0") in {"1", "true", "True"}

# Allow localhost & Codespaces preview by default; override via env when deploying.
ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,0.0.0.0,.app.github.dev",
)

# Required for POST/CSRF on those hosts (Codespaces + local)
CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:8000,http://127.0.0.1:8000,https://*.app.github.dev",
)

# ---------- Application definition ----------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    
    'accounts',
    'aquariums',
    'calculator',
    
    'crispy_forms',
    'crispy_bootstrap5',
    
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = "ReefTracker.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ReefTracker.wsgi.application"

# ---------- Database ----------
# Use DATABASE_URL from env. Fall back to SQLite for local dev if missing.
# ssl_require=True ensures Codespaces → Render uses SSL even if the URL lacks ?sslmode=require
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=False,  # PostgreSQL supports SSL, SQLite will ignore this
    )
}

# If behind a proxy that terminates SSL (Render), honor X-Forwarded-Proto
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ---------- Password validation ----------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ---------- Internationalization ----------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ---------- Static files ----------
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "/static/"

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ---------- Defaults ----------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LOGIN_URL = "account_login"
#LOGIN_REDIRECT_URL = 'accounts:home'
#LOGOUT_REDIRECT_URL = 'landing'



MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'





# ==========================================
# DJANGO-ALLAUTH CONFIGURATION
# ==========================================
SITE_ID = 1 # Required by the sites framework

# Authentication backends allow you to log in via email OR username
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Registration Rules (Modern Syntax)
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

# mandatory
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# Where to send users after they log in or log out
LOGIN_REDIRECT_URL = 'accounts:home'
ACCOUNT_LOGOUT_REDIRECT_URL = 'landing' # Assuming 'landing' is your front page URL name

# For local development: Print the verification emails to the terminal instead of actually sending them
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

ACCOUNT_SESSION_REMEMBER = True