# .render.yaml
services:
  - type: web
    name: reeftracker
    env: python    
    rootDir: ReefTracker/ReefTracker
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ReefTracker.wsgi:application

