import os                                                                                                                                                                                                                                                                                       
import sys                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                
# 1. Bootstrap Django environment                                                                                                                                                                                                                                                               
sys.path.append(os.path.dirname(os.path.abspath(__file__)))                                                                                                                                                                                                                                     
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ReefTracker.settings')                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                
import django                                                                                                                                                                                                                                                                                   
django.setup()                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                
# Now we can safely import Django models                                                                                                                                                                                                                                                        
from django.contrib.auth.models import User                                                                                                                                                                                                                                                     
from aquariums.models import Aquariums, Species, Livestock                                                                                                                                                                                                                                      
from fastmcp import FastMCP

# 2. Initialize FastMCP                                                                                                                                                                                                                                                                         
mcp = FastMCP("ReefTracker Tools")                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                
@mcp.tool()                                                                                                                                                                                                                                                                                     
def get_aquarium_list() -> str:                                                                                                                                                                                                                                                                 
    """                                                                                                                                                                                                                                                                                         
    Retrieves all aquariums registered in ReefTracker, including sizes, types, and species.                                                                                                                                                                                                     
    """                                                                                                                                                                                                                                                                                         
    try:                                                                                                                                                                                                                                                                                        
        aquariums = Aquariums.objects.all()                                                                                                                                                                                                                                                     
        if not aquariums.exists():                                                                                                                                                                                                                                                              
            return "No aquariums registered in ReefTracker."                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                
        result = []                                                                                                                                                                                                                                                                             
        for aq in aquariums:                                                                                                                                                                                                                                                                    
            aq_info = (                                                                                                                                                                                                                                                                         
                f"- Name: {aq.name}\n"                                                                                                                                                                                                                                                          
                f"  Type: {aq.type}\n"                                                                                                                                                                                                                                                          
                f"  Size: {aq.size}\n"                                                                                                                                                                                                                                                          
                f"  Volume: {aq.volume_liters or 'N/A'} L\n"                                                                                                                                                                                                                                    
                f"  Owner: {aq.user.username}"                                                                                                                                                                                                                                                  
            )                                                                                                                                                                                                                                                                                   
            result.append(aq_info)                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                
        return "Aquariums registered:\n" + "\n".join(result)                                                                                                                                                                                                                                    
    except Exception as e:                                                                                                                                                                                                                                                                      
        return f"Error querying ReefTracker DB: {str(e)}"                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                
@mcp.tool()                                                                                                                                                                                                                                                                                     
def get_aquarium_livestock(aquarium_name: str) -> str:                                                                                                                                                                                                                                          
    """                                                                                                                                                                                                                                                                                         
    Retrieves the livestock (fish, corals, invertebrates) currently inside a specific aquarium.                                                                                                                                                                                                 
    """                                                                                                                                                                                                                                                                                         
    try:                                                                                                                                                                                                                                                                                        
        aq = Aquariums.objects.filter(name__iexact=aquarium_name).first()                                                                                                                                                                                                                       
        if not aq:                                                                                                                                                                                                                                                                              
            return f"Aquarium named '{aquarium_name}' was not found."                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                
        livestock = aq.livestock_items.all()                                                                                                                                                                                                                                                    
        if not livestock.exists():                                                                                                                                                                                                                                                              
            return f"No livestock recorded in aquarium '{aq.name}'."                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                
        result = []                                                                                                                                                                                                                                                                             
        for item in livestock:                                                                                                                                                                                                                                                                  
            name = item.species.common_name if item.species else item.custom_name                                                                                                                                                                                                               
            result.append(f"- {name} (Qty: {item.quantity}) - Notes: {item.notes or 'None'}")                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                
        return f"Livestock in aquarium '{aq.name}':\n" + "\n".join(result)                                                                                                                                                                                                                      
    except Exception as e:                                                                                                                                                                                                                                                                      
        return f"Error retrieving livestock: {str(e)}"                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                
# 3. Launch as an SSE Server on port 8003                                                                                                                                                                                                                                                       
if __name__ == "__main__":
    print("Starting ReefTracker MCP SSE Server on port 8003...", flush=True)
    mcp.run(transport="sse", host="0.0.0.0", port=8003)