# Generated by Django 5.2.14 on 2026-06-01 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0002_livestock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('ph', 'pH'), ('temp', 'Temperature'), ('salinity', 'Salinity'), ('dkh', 'Alkalinity (dKH)'), ('calcium', 'Calcium'), ('magnesium', 'Magnesium'), ('nitrate', 'Nitrate (NO3)'), ('phosphate', 'Phosphate (PO4)'), ('ammonia', 'Ammonia (NH3/NH4+)'), ('nitrite', 'Nitrite (NO2-)')], max_length=20)),
                ('min_value', models.FloatField(help_text='Minimum acceptable value')),
                ('max_value', models.FloatField(help_text='Maximum acceptable value')),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_zones', to='aquariums.aquariums')),
            ],
            options={
                'unique_together': {('aquarium', 'parameter')},
            },
        ),
    ]
