# Generated by Django 5.2.14 on 2026-06-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CAL', 'Calcium'), ('MAG', 'Magnesium'), ('ALK', 'Alkalinity')], max_length=3)),
                ('description', models.CharField(max_length=200)),
                ('PPMPerLiter', models.FloatField(help_text='PPM increase per 1ml in 1 Liter of water')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
