# Generated by Django 5.2.14 on 2026-05-31 21:57

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=40)),
                ('scientific_name', models.CharField(blank=True, max_length=40, null=True)),
                ('category', models.CharField(choices=[('FISH', 'Fish'), ('CORAL', 'Coral'), ('INVERT', 'Invertebrate'), ('MACRO', 'Macroalgae')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Species',
                'ordering': ['category', 'common_name'],
            },
        ),
        migrations.CreateModel(
            name='Aquariums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('volume_liters', models.FloatField(blank=True, help_text='Net water volume in liters', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquariums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, help_text='Use this if species is not in the list', max_length=100, null=True)),
                ('date_acquired', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='livestock_images/')),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_items', to='aquariums.aquariums')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livestock_instances', to='aquariums.species')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='aquariums.aquariums')),
                ('livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='aquariums.livestock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('ph', 'pH'), ('temp', 'Temperature'), ('salinity', 'Salinity'), ('dkh', 'Alkalinity (dKH)'), ('calcium', 'Calcium'), ('magnesium', 'Magnesium'), ('nitrate', 'Nitrate (NO3)'), ('phosphate', 'Phosphate (PO4)'), ('ammonia', 'Ammonia (NH3/NH4+)'), ('nitrite', 'Nitrite (NO2-)')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(help_text='Measurement unit, validated against parameter type', max_length=20)),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='aquariums.aquariums')),
            ],
            options={
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['aquarium', 'parameter', 'measured_at'], name='aquariums_w_aquariu_867148_idx')],
            },
        ),
    ]
