# Generated by Django 5.2.14 on 2026-06-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='How many of this species?'),
        ),
    ]
