# Generated by Django 5.2.3 on 2025-09-12 04:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_magnesiumproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calciumproducts',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='magnesiumproducts',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='calciumproducts',
            name='PPMPerLiter',
            field=models.FloatField(help_text='PPM per liter of solution'),
        ),
        migrations.AlterField(
            model_name='calciumproducts',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='magnesiumproducts',
            name='PPMPerLiter',
            field=models.FloatField(help_text='PPM per liter of solution'),
        ),
        migrations.AlterField(
            model_name='magnesiumproducts',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Common name of the livestock', max_length=100)),
                ('species', models.CharField(blank=True, help_text='Scientific name', max_length=100)),
                ('livestock_type', models.CharField(choices=[('fish', 'Fish'), ('coral', 'Coral'), ('invertebrate', 'Invertebrate'), ('crustacean', 'Crustacean'), ('mollusk', 'Mollusk'), ('anemone', 'Anemone'), ('algae', 'Algae'), ('sponge', 'Sponge'), ('urchin', 'Urchin / Echinoderm'), ('other', 'Other')], default='other', max_length=20)),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('health_status', models.CharField(default='healthy', help_text='Current health status', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this livestock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to='myapp.aquariums')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
