# Generated by Django 5.2.3 on 2025-09-12 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_calciumproducts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquariums',
            name='volume_liters',
            field=models.FloatField(blank=True, help_text='Net water volume in liters', null=True),
        ),
        migrations.CreateModel(
            name='WaterParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('ph', 'pH'), ('temp', 'Temperature'), ('salinity', 'Salinity'), ('dkh', 'Alkalinity (dKH)'), ('calcium', 'Calcium'), ('magnesium', 'Magnesium'), ('nitrate', 'Nitrate (NO3)'), ('phosphate', 'Phosphate (PO4)'), ('ammonia', 'Ammonia (NH3/NH4+)'), ('nitrite', 'Nitrite (NO2-)')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(help_text='Measurement unit, validated against parameter type', max_length=20)),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='myapp.aquariums')),
            ],
            options={
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['aquarium', 'parameter', 'measured_at'], name='myapp_water_aquariu_227359_idx')],
            },
        ),
    ]
